spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dbUnimail
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver
    testOnBorrow: true
    validationQuery: SELECT 1
  jpa:
    show-sql: true
    hibernate:
      ddlAuto: create
  data:
    jpa:
      repositories:
        enabled: true


server:
  port: 8089